replicas: 1
interface: wg0
listenPort: 51820
network: 10.10.0.1/24
networkInterface: eth0
mtu: 1280
image: ghcr.io/denefoster/helm-test:v1.0.7
dnsForward: /etc/resolv.conf
dnsPrivateZone: internal
deployKind: DaemonSet
metrics: true
